name 'example42-activemq'
version '2.0.15'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'https://github.com/example42/puppet-activemq'
source 'https://github.com/example42/puppet-activemq'
summary 'Puppet module for activemq'
description 'This module installs and manages activemq. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
dependency 'example42/yum', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/java', '>=2.0.0'
